employeedb/employee/forms.py
"""
Forms for adding and editing Employee Details
"""
from wtforms import (Form, BooleanField, TextField, TextAreaField,
        validators, IntegerField, SelectField, BooleanField, FileField, ValidationError,DateField,DateTimeField,PasswordField,FormField)


class AddressForm(Form):
    name = TextField(
        "Name", 
        [validators.Required('Name cannot be empty')]
        ) 

    Street = TextField(
        "Street", 
        [validators.Required('street cannot be empty')]
        )
    city = TextField(
        "city", 
        [validators.Required('city  cannot be empty')]
        )
    state = TextField(
        "state", 
        [validators.Required('state Name cannot be empty')]
        )
    pincode = TextField(
        "Pin Code",
        [validators.Required('Mobile No. should be number or can not be empty'),validators.Regexp("\d{6}",  message=u'Invalid input.')]
        )





class EmployeeForm(Form):
    empid = TextField(
        "Employee Id", 
        [validators.Required('Employee Id cannot be empty')]
        )
    
    empname = TextField(
        "Employee Name", 
        [validators.Required('Employee Name cannot be empty')]
        )
    
    fathername = TextField(
        "Father Name",
        [validators.Required('Father name  cannot be empty')]
        )
    mothername = TextField(
        "Mother Name",
        [validators.Required('Mother  name  cannot be empty')]
        )
    
    qualification = TextField(
        "Qualification Details",
        [validators.Required('Qualification Details cannot be empty')]
        )
    
    nationality = TextField(
        "Nationality",
        [validators.Required('Nationality cannot be empty')]
        )
    '''
    dob = DateField('Date:', validators=[DateRange(date(1919,1,1), date(2012,4,20))])
    '''
    dob= DateTimeField("Date of Birth",format='%m-%d-%Y')
   
    doj = DateTimeField("Date of Join",format='%m-%d-%Y')
        
    gender = SelectField(
         "Gender", 
         choices = [('male','MALE'),('female','FEMALE')])

    mstatus=SelectField(
        "Marital Status",
        choices = [('Single','SINGLE'),('Married','MARRIED')]
        )
    
    sname=TextField(
        "Spouse Name"
                )

    designation = TextField(
        "Designation",
        [validators.Required('Designation cannot be empty')]
        )

    department = TextField(
        "Department",
        [validators.Required('Department cannot be empty')]
        )

    email = TextField(
        "Email ID (for Payslip)",
        [validators.Required('Email ID  cannot be empty'),validators.Email(message="email should be in proper formate")]
        )

    pan = TextField(
        "PAN No.",
        [validators.Required('PAN card No. cannot be empty')]
        )

    mobile = TextField(
        "Mobile No.",
        [validators.Required('Mobile No. should be number or can not be empty'),validators.Regexp("\d{2}",  message=u'Invalid input.')]
        )
    address = FormField(AddressForm)

class UserForm(Form):
    username = TextField('Username', [validators.Length(min=4, max=25)])
    password = PasswordField('Password', [validators.Required('password can not be empty')
    ])

    
    
    

employeedb/employee/__init__.py
from .views import employee

employeedb/employee/views.py
from flask import Flask, request, render_template, redirect, url_for,Blueprint,flash,session
from forms import EmployeeForm,UserForm
from models.employeedb import Employee
from models.dbconfig import db
from models.user import UserLog as User
from app import app
from flask.ext.login import (LoginManager, current_user, login_required,login_user, logout_user,confirm_login, fresh_login_required)



employee = Blueprint('employee', __name__, template_folder='templates', static_folder='static')


@employee.route('/',methods=["GET", "POST"])
def index():
    return render_template('index.html')  



@employee.route('/list',methods=["GET", "POST"])
def show_all():
    emps = db.Employee.find()
    return render_template('employee_list.html', emps=emps)  

@employee.route('/views/<employee>',methods=["GET", "POST"])
def show_deatails(employee):
    emp=db.Employee()
    emp=emp.get_by_id(employee)
    return render_template('employee_views.html', emps=emp)                        


@employee.route('/new', methods=["GET", "POST"])
def add_employee():
    f =  EmployeeForm(request.form)
    if request.method == 'POST' and f.validate():
        emp = db.Employee()
        emp._id = f.empid.data
        emp.empname = f.empname.data
        emp.fathername = f.fathername.data
        emp.mothername = f.mothername.data
        emp.qualification = f.qualification.data
        emp.nationality = f.nationality.data
        emp.dob = f.dob.data
        emp.doj = f.doj.data
        emp.gender = f.gender.data
        emp.mstatus = f.mstatus.data
        emp.sname = f.sname.data
        emp.designation = f.designation.data
        emp.department = f.department.data
        emp.email = f.email.data
        emp.pan = f.pan.data
        emp.mobile = f.mobile.data
        emp.save()
        return redirect(url_for('.show_all'))
    return render_template('new_employee.html', form=f)


@employee.route('/edit/<employee>', methods=["GET", "POST"])
@login_required
def edit_employee(employee):
    emp=db.Employee()
    emp=emp.get_by_id(employee)
    form=EmployeeForm(request.form,obj=emp)
    form.empid.data=employee
    if request.method == 'POST' and form.validate():
        e=db.Employee()
        e.update(form,employee)
        return redirect(url_for('.show_all'))  
    return render_template('edit_employee.html',form=form,emp=emp)

@employee.route('/delete/<employee>', methods=["GET", "POST"])
@login_required
def delete_employee(employee):
    emp=db.Employee()
    emp.delete(employee)
    return redirect(url_for(".show_all"))




   

employeedb/employee/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Employee</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="../static/css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 9px 0;
      }
    </style>
    <link href="../static/css/bootstrap-responsive.css" rel="stylesheet">
    
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">EMPLOYEE DB</a>
          <div class="nav-collapse collapse">
            <p class="navbar-text pull-right">
                {% if current_user.is_authenticated() %}
                    <a href="{{ url_for('logout') }}" class="navbar-link">log out</a>
              {% else %}
               
              {% endif %}
            </p>
            <ul class="nav">
              <li class="active"><a href="#">Home</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

      <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Action</li>
              <li><a href="{{ url_for('.show_all') }}">List</a></li>
              <li><a href="{{ url_for('.add_employee') }}">Add new</a></li>
              <li><a href="#">views</a></li>
              <li><a href="#">Delete</a></li>
              <li><a href="#">Edit</a></li>
              
            </ul>
         
        </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <div class="hero-unit">
            {% block body %}{% endblock %}
          </div>
          
          
        </div><!--/span-->
      </div><!--/row-->

      <hr>

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div><!--/.fluid-container-->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="../static/js/jquery.js"></script>
    <script src="../employee/static/js/bootstrap-transition.js"></script>
    <script src="../employee/static/js/bootstrap-alert.js"></script>
    <script src="../employee/static/js/bootstrap-modal.js"></script>
    <script src="../employee/static/js/bootstrap-dropdown.js"></script>
    <script src="../employee/static/js/bootstrap-scrollspy.js"></script>
    <script src="../employee/static/js/bootstrap-tab.js"></script>
    <script src="../employee/static/js/bootstrap-tooltip.js"></script>
    <script src="../employee/static/js/bootstrap-popover.js"></script>
    <script src="../employee/static/js/bootstrap-button.js"></script>
    <script src="../employee/static/js/bootstrap-collapse.js"></script>
    <script src="../employee/static/js/bootstrap-carousel.js"></script>
    <script src="../employee/static/js/bootstrap-typeahead.js"></script>
   
  </body>
</html>

employeedb/employee/templates/edit_employee.html
{% extends "base.html" %}
{% block body %}


 <center> <h2>Edit Employee Details</h2>
  <form action="" method=post>
<table>
  {% for field in form %}
    <tr>
        <th>{{ field.label }}</th>
        <td>{{ field }}</td>
        
        {% if field.errors %}
       <td>
        {% for error in field.errors %}
          <li>{{ error }}</li>
        {% endfor %}
        </td>
      {% endif %}
    </tr>
{% endfor %}
</table>

     <input type=submit value="update">
</form>
<script src="../static/js/jquery.js"></script>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.9.0/themes/base/jquery-ui.css" />
<script>
    $(function() {
        $("#dob").datepicker({ dateFormat: "mm-dd-yy" });
        $("#doj").datepicker({ dateFormat: "mm-dd-yy" });
    });
</script>
{% endblock %}

employeedb/employee/templates/employee_list.html
{% extends "base.html" %}
{% block body %}
{% with messages = get_flashed_messages() %}
  {% if messages %}
    <ul class=flashes>
    {% for message in messages %}
      <li>{{ message }}</li>
    {% endfor %}
    </ul>
  {% endif %}
{% endwith %}
<div class="rsec">
<div class="formcontent">
<center><h2>list of Employee</h2></center>
<table class="well"><tr>
		    <th style="width: 50px">Emp_Id</th>
            <th style="width: 200px">Employee Name</th>
            <th style="width: 200px"><strong>Email Id</strong></th>
            <th style="width: 200px"><strong>Mobile No.</strong></th>
			<th style="width: 200px"><strong>Action</strong></th>
        </tr>
	    {% for emp in emps %}
        <tr class="{{ entry_class }}">
            <td>{{emp._id}}</td>
			<td>{{emp.empname}}</td>
            <td>{{emp.email}}</td>
            <td>{{emp.mobile}}</td>&nbsp;&nbsp;
            <td>
                <a href="{{url_for('.show_deatails', employee=emp._id)}}">views</a>
            </td>
	
        </tr>
        {% endfor %}
    
    
</table>
</div>
</div>
{% endblock %}

employeedb/employee/templates/employee_views.html
{% extends "base.html" %}
{% block body %}
{% with messages = get_flashed_messages() %}
  {% if messages %}
    <ul class=flashes>
    {% for message in messages %}
      <li>{{ message }}</li>
    {% endfor %}
    </ul>
  {% endif %}
{% endwith %}
<div class="rsec">
    <h2>Employee Details</h2>
    <div class="formcontent">
        <table class="well">
                <tr >
                    <th style="width: 160px">fields </th> 
                    <th style="width: 160px"> values</th>
                </tr>	
                <tr class="{{ entry_class }}">
                    <td>Emp_Id </td> 
                    <td> {{emps._id}}</td>
                </tr>
		        <tr>
                     <td>Employee Name </td>
                     <td>{{emps.empname}}</td>
                </tr>
                <tr>
                     <td>Father Name/td>
                     <td>{{emps.fathername}}</td>
                </tr>
                <tr>
                     <td>Mother Name</td>
                     <td>{{emps.mothername}}</td>
                </tr>
                <tr>
                     <td>Qualification</td>
                     <td>{{emps.qualification}}</td>
                </tr>
                <tr>
                    <td>Nationality</td>
                    <td> {{emps.nationality}}</td>
                </tr>
                <tr>
                    <td>Date of birth</td>
                    <td> {{emps.dob}}</td>
                </tr>
                <tr>
                    <td>Date of Join</td>
                    <td>{{emps.doj}}</td>
                </tr>
                <tr>
                    <td>Gender</td>
                    <td>{{emps.gender}}</td>
                </tr>
                <tr>
                    <td>Designation</td>
                    <td>{{emps.designation}}</td>
                </tr>
                <tr>
                    <td>Department</td>
                    <td>{{emps.department}}</td>
                </tr>
                <tr>
                    <td>Email Id</td>
                    <td>{{emps.email}}</td>
                </tr>
                <tr>
                    <td>Mobile No.</td>
                    <td> {{emps.mobile}}</td>
                </tr>
               
            
            
        </table>
    </div>
</div>
 <div class="rsec">
    <div class="formcontent">

        <table class="well">
                <tr >
                        <th style="width: 160px"><a href="{{url_for('employee.delete_employee', employee=emps._id)}}">Delete &nbsp;&nbsp;</a></th> 
                        <th style="width: 160px"><a href="{{url_for('employee.edit_employee', employee=emps._id)}}">Edit</a></th>
                </tr>
        </table>

    </div>
</div>


{% endblock %}

employeedb/employee/templates/new_employee.html
{% extends "base.html" %}
{% block body %}
<script src="../static/js/jquery.js"></script>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.9.0/themes/base/jquery-ui.css" />
 <center> <h2>Add Employee Details</h2>
  <form method=post action="">
<table>
  {% for field in form %}
    <tr>
        <th>{{ field.label }}</th>
        <td>{{ field }}</td>
        {% if field.errors %}
       <td>
        {% for error in field.errors %}
          <li>{{ error }}</li>
        {% endfor %}
        </td>
      {% endif %}
    </tr>
{% endfor %}
</table>

     <input type=submit value="Add">
  </form> <center>
 <script>
    $(function() {
        $("#dob").datepicker({ dateFormat: "mm-dd-yy" });
        $("#doj").datepicker({ dateFormat: "mm-dd-yy" });
    });
</script>

{% endblock %}