employeedb/employee/views.py
from flask import Flask, request, render_template, redirect, url_for,Blueprint,flash,session
from forms import EmployeeForm,UserForm
from models.employeedb import Employee
from models.dbconfig import db
from models.user import UserLog as User
from app import app
from flask.ext.login import (LoginManager, current_user, login_required,login_user, logout_user,confirm_login, fresh_login_required)



employee = Blueprint('employee', __name__, template_folder='templates', static_folder='static')


@employee.route('/',methods=["GET", "POST"])
def index():
    return render_template('index.html')  



@employee.route('/list',methods=["GET", "POST"])
def show_all():
    emps = db.Employee.find()
    return render_template('employee_list.html', emps=emps)  

@employee.route('/views/<employee>',methods=["GET", "POST"])
def show_deatails(employee):
    emp=db.Employee()
    emp=emp.get_by_id(employee)
    return render_template('employee_views.html', emps=emp)                        


@employee.route('/new', methods=["GET", "POST"])
def add_employee():
    f =  EmployeeForm(request.form)
    if request.method == 'POST' and f.validate():
        emp = db.Employee()
        emp._id = f.empid.data
        emp.empname = f.empname.data
        emp.fathername = f.fathername.data
        emp.mothername = f.mothername.data
        emp.qualification = f.qualification.data
        emp.nationality = f.nationality.data
        emp.dob = f.dob.data
        emp.doj = f.doj.data
        emp.gender = f.gender.data
        emp.mstatus = f.mstatus.data
        emp.sname = f.sname.data
        emp.designation = f.designation.data
        emp.department = f.department.data
        emp.email = f.email.data
        emp.pan = f.pan.data
        emp.mobile = f.mobile.data
        emp.save()
        return redirect(url_for('.show_all'))
    return render_template('new_employee.html', form=f)


@employee.route('/edit/<employee>', methods=["GET", "POST"])
@login_required
def edit_employee(employee):
    emp=db.Employee()
    emp=emp.get_by_id(employee)
    form=EmployeeForm(request.form,obj=emp)
    form.empid.data=employee
    if request.method == 'POST' and form.validate():
        e=db.Employee()
        e.update(form,employee)
        return redirect(url_for('.show_all'))  
    return render_template('edit_employee.html',form=form,emp=emp)

@employee.route('/delete/<employee>', methods=["GET", "POST"])
@login_required
def delete_employee(employee):
    emp=db.Employee()
    emp.delete(employee)
    return redirect(url_for(".show_all"))




   

employeedb/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Employee</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="../static/css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 9px 0;
      }
    </style>
    <link href="../static/css/bootstrap-responsive.css" rel="stylesheet">
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.9.0/themes/base/jquery-ui.css" />
    
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">EMPLOYEE DB</a>
          <div class="nav-collapse collapse">
            <p class="navbar-text pull-right">
                {% if current_user.is_authenticated() %}
                    <a href="{{ url_for('logout') }}" class="navbar-link">log out</a>
              {% else %}
                    <a href="{{ url_for('login') }}" class="navbar-link">login</a>
              {% endif %}
            </p>
            <ul class="nav">
              <li class="active"><a href="{{ url_for('employee.index') }}">Home</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

      <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Action</li>
              <li><a href="{{ url_for('employee.show_all') }}">List</a></li>
              <li><a href="{{ url_for('employee.add_employee') }}">Add new</a></li>
              
              
            </ul>
         
        </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <div class="hero-unit">
            {% block body %}{% endblock %}
          </div>
          
          
        </div><!--/span-->
      </div><!--/row-->

      <hr>

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div><!--/.fluid-container-->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="../static/js/jquery.js"></script>
    <script src="../static/js/bootstrap-transition.js"></script>
    <script src="../static/js/bootstrap-alert.js"></script>
    <script src="../static/js/bootstrap-modal.js"></script>
    <script src="../static/js/bootstrap-dropdown.js"></script>
    <script src="../static/js/bootstrap-scrollspy.js"></script>
    <script src="../static/js/bootstrap-tab.js"></script>
    <script src="../static/js/bootstrap-tooltip.js"></script>
    <script src="../static/js/bootstrap-popover.js"></script>
    <script src="../static/js/bootstrap-button.js"></script>
    <script src="../static/js/bootstrap-collapse.js"></script>
    <script src="../static/js/bootstrap-carousel.js"></script>
    <script src="../static/js/bootstrap-typeahead.js"></script>
    <script src="http://code.jquery.com/ui/1.9.0/jquery-ui.js"></script>
  </body>
</html>

employeedb/templates/index.html
{% extends "base.html" %}
{% block body %}
<p> this is Employee Data base </p>
    


{% endblock %}

employeedb/templates/login.html
{% extends "base.html" %}

{% block body %}
    {% with messages = get_flashed_messages() %}
  {% if messages %}
    <ul class=flashes>
    {% for message in messages %}
      <li>{{ message }}</li>
    {% endfor %}
    </ul>
  {% endif %}
{% endwith %}
  <h2>Login</h2>
  <form action="" method=post>
    <dl>
      <dt>Username:
      <dd><input type=text name=username>
      <dt>password:
      <dd><input type=password name=pwd>
      <dt>Remember Me:
      <dd><input type=checkbox name=remember value=yes>
      <dd><input type=submit value=Login>
    </dl>
  </form>
{% endblock %}